source("a_dSVA_functions.R")
source("a_other_method_functions.R")
source("s_sim_functions.R")
source("s_util_functions.R")
library(extraDistr)
library(statmod)
library(MASS)
library(dplyr)
library(tidyr)
library(ggplot2)
library(statmod)
library(PCAtools)
library(paran)
library(sva)
library(DescTools)
library(microbenchmark)

## other benchmark methods
library(limma)
library(RUVSeq)
